apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 8080           # Kubernetes içindeki servis portu
      targetPort: 8080     # Container içindeki port
      nodePort: 30002      # Dış dünyadan erişim için açılan port (http://localhost:30002)